{{- $svc := .Values.webFrontend -}}
{{- $name := "frontend" -}}
{{- if $svc.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cashback.componentName" (dict "root" . "name" $name) }}
  labels:
    {{- include "cashback.commonLabels" (dict "root" . "component" $name) | nindent 4 }}
spec:
  replicas: {{ $svc.replicas }}
  selector:
    matchLabels:
      {{- include "cashback.componentSelector" (dict "root" . "component" $name) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cashback.commonLabels" (dict "root" . "component" $name) | nindent 8 }}
    spec:
      serviceAccountName: {{ include "cashback.serviceAccount" . }}
      securityContext:
        {{- toYaml .Values.global.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $name }}
          image: {{ include "cashback.image" (dict "root" . "name" $name "image" $svc.image) }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - { containerPort: {{ $svc.port }}, name: http, protocol: TCP }
          resources:
            {{- toYaml $svc.resources | nindent 12 }}
          livenessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            {{- toYaml .Values.global.containerSecurityContext | nindent 12 }}
{{- end }}
