{{- if .Values.global.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cashback.serviceAccount" . }}
  labels:
    {{- include "cashback.commonLabels" (dict "root" . "component" "serviceaccount") | nindent 4 }}
  {{- with .Values.global.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
